SELECT
                OH.ONHAND_REF,
                OH.SHPMNT_REF,
                OH.SHIPMENT_TYPE,
                FRD.DATE_CREATE AS "FRD_DATE",
                FRT.DATE_CREATE AS "FRT_DATE"
FROM            EXPORT.ONHAND_HDR OH

LEFT JOIN       EXPORT.STAT_ITEM FRD ON FRD.INVOICE_REF in(OH.ONHAND_REF, OH.SHPMNT_REF) and FRD.STAT_CODE = 'FRD'
LEFT JOIN       EXPORT.STAT_ITEM FRT ON FRT.INVOICE_REF in(OH.ONHAND_REF, OH.SHPMNT_REF) and FRT.STAT_CODE = 'FRT'   

WHERE           --OH.DATE_CREATE > '118102000000000000'           
                FRD.DATE_STAT >=( CAST( YEAR( CURRENT TIMESTAMP - 1 DAYS ) - 1900 AS DECIMAL ) *
	        1000000000000000 ) +( CAST( MONTH( CURRENT TIMESTAMP - 1 DAYS ) AS DECIMAL ) * 10000000000000
                ) +( CAST( DAY( CURRENT TIMESTAMP - 1 DAYS ) AS DECIMAL ) * 100000000000 )
 
and             OH.SHIPMENT_TYPE in ('OHA', 'EHA', 'EDA', 'CHA', 'ICA', 'DCA')